### ISSUE TITLE
maven plugin download fails

### ISSUE THREAD

**Issue by riponbanik** [oneops/cmsdal#81]
Shows the following error - Jenkins version is 1.651.3

[ERROR] Plugin org.apache.maven.plugins:maven-clean-plugin:2.5 or one of its dependencies could not be resolved: Failed to read artifact descriptor for org.apache.maven.plugins:maven-clean-plugin:jar:2.5: Could not transfer artifact org.apache.maven.plugins:maven-clean-plugin:pom:2.5 from/to central (https://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:443 [repo.maven.apache.org/151.101.24.215] failed: Connection timed out (Connection timed out) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
[JENKINS] Archiving /home/oneops/build/build-wf/workspace/cmsdal/pom.xml to com.oneops.cms/cmsdal/1.0.4/cmsdal-1.0.4.pom
Set build name.

**Comment by mosabua** [comment]
Issue tracking has moved to Walmart internal JIRA and https://github.com/oneops/oneops
